### ISSUE TITLE
assets.ts, assetUtils.ts should be valid TypeScript in strict mode

### ISSUE THREAD

**Issue by ignlg** [rroylance/phaser-ce-npm-webpack-typescript-starter-project#29]
If `strict` is activated, via `"strict": true,` at `tsconfig.json`, TypeScript throws many errors at `utils/assetUtils.ts`, but they're just a side effect of how `assets.ts` is constructed.

This kind of error:
```log
ERROR in ./src/utils/assetUtils.ts
(10,48): error TS7017: Element implicitly has an 'any' type because type 'typeof Images' has no index signature.
. . .
ERROR in ./src/utils/assetUtils.ts
(22,48): error TS7017: Element implicitly has an 'any' type because type 'typeof Spritesheets' has no index signature.
```
thrown at code that accesses static methods through dynamic class definitions inside namespaces:
```ts
if (!this.game.cache.checkImageKey(Assets.Images[image].getName())) {
```

TypeScript cannot know what type `Assets.Images[image]` is, and me neither as each asset generates a class.

After some refactoring, I've found myself rewriting `generateAssetsClass.js`, and as I'd like to collaborate with this project, I don't want to diverge that much without further debate about options available.

Some relevant points:
* Namespaces are not used as such and just as keys.
* Classes are not created to be instantiated and just as containers.

The idea I'm studying is to create some classes:
```ts
export class AssetImage {
    constructor(public name: string) {
    }
    getName(): string {
        return this.name;
    }
}

export class AssetImagePNG extends AssetImage {
    constructor(name: string, public getPNG: () => string) {
        super(name);
    }
}
```

and then generate the code with instances like:
```ts
const Assets = {
    Images: {
        backgroundTemplate: new AssetImagePNG("background_template", () => require("assets/images/background_template.png"))
    }
};
```

The main advantage should be that TS can follow those types and it simplifies the generator and the generated `assets.ts`.

Issues? Options? Ideas?

**Comment by rroylance** [comment]
I like it, nice and clean. I'd be happy to take a look at your complete solution and merge it in when it's ready.
