### ISSUE TITLE
Security risk for webpack-dev-server

### ISSUE THREAD

**Issue by jdeblander** [rroylance/phaser-ce-npm-webpack-typescript-starter-project#68]
**Describe the bug**
When using `npm audit`, this results in 1 **high severity** vulnerability for _webpack-dev-server_ v3.1.10.

**To Reproduce**
1. run `npm audit`
2. See audit report

**Expected behavior**
No vulnerabilities 😄 

**Report**
```
                       === npm audit security report ===

# Run  npm install webpack-dev-server@3.1.14  to resolve 1 vulnerability

  High            Missing Origin Validation

  Package         webpack-dev-server

  Dependency of   webpack-dev-server

  Path            webpack-dev-server

  More info       https://nodesecurity.io/advisories/725
```

**Additional context**
Updating _webpack-dev-server_ to 3.1.14 should fix this.

I've made a pull request #69.

**Comment by rroylance** [comment]
Thank you very much @jdeblander!
