### ISSUE TITLE
[REQUEST] I've made a game using your boilerplate

### ISSUE THREAD

**Issue by tuskat** [rroylance/phaser-ce-npm-webpack-typescript-starter-project#72]
I didn't know how to contact you so I thought it would be the easiest way.
I've made a game called R0d3nt, using your boilerplate.

[you can see the repo here](https://github.com/tuskat/R0d3nt)
[and play it there](https://tuskat.itch.io/r0d3nt)

Game: R0d3nt
Author: tuskat

Github Repo: https://github.com/tuskat/R0d3nt

Description: Futur1st1c P3st C0ntr0l

Thumbnail: https://img.itch.zone/aW1nLzIyMzU1NjIucG5n/315x250%23c/ZbaHXr.png

**Comment by rroylance** [comment]
Thanks @tuskat! Looks and plays very nice!

I've added it to the README :)
